### ISSUE TITLE
Interactions.Climbable should not be Distance Grabbable by default

### ISSUE THREAD

**Issue by jorgeolothar** [ExtendRealityLtd/Tilia.Locomotors.Climbing.Unity#64]
## Is your feature request related to a problem?

It can be frustrating to support both distance grabbing and climbables in the same scene, since by default the distance grabber can lock on to the Interactable child in the climbable. You grab a climbable at a distance by default, causing all sorts of deformations.

## Describe the solution you'd like

It would be nice for an out-of-the-box solution that makes climbables not distance grabbable.

## Describe alternatives you've considered

My current working solution is adding an "InvalidDistanceGrab" tag on the climbable's interactable, then setting up a target validity for the distance grabber that rejects them. Every climbable must then have this tag, which can be easy to forget.

Unsure if setting the climbable to static would solve the grabbing part, but it would still show the distance grabber pointer.

## Additional context

VRTK V4 Dev BrainDump - [0007] introduced distance grabbing. It was difficult to climb the wall in the scene, since every now and then the interactor would be at a distance from the wall while climbing, distance grabbing the whole wall into the interactor.

**Comment by thestonefox** [comment]
I think a default tag on climbable objects to denote they are climbable is probably the best solution.

Having the distance grabber ignore this by default would mean the distance grabber would need to know about the climbing repo to have this logic.

Maybe at best the `Climb` prefab could have two rules auto created on them for `Allow Climbing` and `Ignore Climbing`

then at least the fix on the distance grabber is just drag the `Ignore Climbing` rule to the target validity

**Comment by thestonefox** [comment]
Actually this can be done with `string in list` rules. The climbable interactable can have a `string observable list` denoting a certain word like `specialgrab` and the DistanceGrabber can be set up to ignore these objects by default.

Then there's no dependency between the two repos (other than the intrinsic knowledge of this word in the list `specialgrab`)

But then other things could easily be ignored from grabbing by either adding the `String Observable List` onto their Interactable and add `specialgrab` too.

**Comment by extendreality** [comment]
Fixed with https://github.com/ExtendRealityLtd/Tilia.Locomotors.Climbing.Unity/pull/71
