### ISSUE TITLE
Collisions while climbing

### ISSUE THREAD

**Issue by HugoCortell** [ExtendRealityLtd/Tilia.Locomotors.Climbing.Unity#65]
## Is your feature request related to a problem?

I really dislike how you can grab onto a climbable object and just push yourself inside a wall.

## Describe the solution you'd like

Make the player collide with objects whilst climbing.

## Describe alternatives you've considered

Tried to use events to call the solve collisions but that just teleports the player to the nearest floor *after* he's gone through a wall.

## Additional context

Yeah, that's about it.

**Comment by thestonefox** [comment]
Duplicate of https://github.com/ExtendRealityLtd/Tilia.Trackers.PseudoBody.Unity/issues/7
